### ISSUE TITLE
有个驱动导致logo重启

### ISSUE THREAD

**Issue by Qjbtiger** [longmiaohao/Asus-Fx60vm-clover#1]
你好，我是这台机型i5版本，我把你的efi文件放进去后会在出现logo后显示出错后重启，当我删除kext中VoodooI2C.kext驱动后可以正常进系统，但触控板仍然没反应，请问有什么办法吗？

**Comment by longmiaohao** [comment]
你好, 如果只是触摸板不能用的话，你先确认下你的触摸板是不是i2c的接口,可以在window的设备管理中查询，因为我的笔记本是i2c的接口，如果你的触摸板不是i2c的话，那你试一下ps2(https://bitbucket.org/RehabMan/os-x-voodoo-ps2-controller/downloads/)的驱动，或者(https://sourceforge.net/p/edp-osxlatitude/svn/74/tree/kextpacks/PS2Touchpad/SmartTouchpad/ApplePS2SmartTouchPad.kext/),这两个只选其一就好，装好后进入触摸板设置看看，有的时候那里面并不一定显示，但是触摸板是可以用的，具体原因我怀疑是因为电源的问题，我把我的笔记本电源拔了，过会插上就出来了，你也可以试试。还有驱动加载后记得重新构建下缓存。如何还是不能用，那么在启动的时候打开-v，和kextdebug，看看是哪些驱动有加载错误的情况

**Comment by Qjbtiger** [comment]
感谢回复！ps2的方案我曾试过，仍然不能驱动。我已经确认我的触摸版是i2c HID接口，我的笔记本和你的型号是相同的，除了cpu你是i7我是i5不同（当然还有你的网卡），其余配件应该都是相同。我打开了-v和kext调试，错误提示在下显示，显示VoodooI2C.kext中的VoodooGPIO驱动加载错误，但其它提示我看不懂了，我猜测是dsdt补丁在两台电脑上有差异。请问你能说说你是怎么给dsdt打补丁吗？
![45a4cb7bf0ed2ea85e011976581f889](https://user-images.githubusercontent.com/44047419/76979544-07b9e400-6973-11ea-8429-20a833a85087.jpg)

**Comment by longmiaohao** [comment]
dsdt需要用到maciasl这个工具，我已经上传到github，你在进入clover界面时按f4，即可提取系统原始的dsdt信息到你的EFI/clover/acpi/origin里面，这个时候，你就需要用maciasl工具打开里面的dsdt文件，如果能够正常打开，看到里面的内容，那你就可以进行下一步了，反编译的时候，你只需要将dsdt和ssdt开头的文件留下来就好，其他的不需要，下一步就开始点击maciasl内的按钮编译，你需要把所有的error全部干掉，这个过程就很有技巧性了，按我的套路就是把错误的行整体干掉，一般都是一个大括号包括的，只要没有被外部调用，都是可以干掉的，要么你就Google或者百度一下看看有没有相应的补丁或者处理方案，这个过程太多样性，你需要自己去查资料解决掉，当你把这个过程搞利索了，后期如果要打背光或者键盘补丁你也能很快解决的，至于打完后有没有效那就看运气了。这个是一些关于触摸板dsdt的问题处理连接（https://github.com/williambj1/VoodooI2C-PreRelease/blob/master/触摸板补充.md#dsdt-触摸板部分详解）（https://www.penghubingzhou.cn/2019/07/24/VoodooI2C%20DSDT%20Edit%20FAQ/）



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Qjb8668 <notifications@github.com&gt;
发送时间: 2020年3月18日 23:48
收件人: longmiaohao/Asus-Fx60vm-clover <Asus-Fx60vm-clover@noreply.github.com&gt;
抄送: longmiaohao <1043213248@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[longmiaohao/Asus-Fx60vm-clover] 有个驱动导致logo重启 (#1)





 
感谢回复！ps2的方案我曾试过，仍然不能驱动。我已经确认我的触摸版是i2c HID接口，我的笔记本和你的型号是相同的，除了cpu你是i7我是i5不同（当然还有你的网卡），其余配件应该都是相同。我打开了-v和kext调试，错误提示在下显示，显示VoodooI2C.kext中的VoodooGPIO驱动加载错误，但其它提示我看不懂了，我猜测是dsdt补丁在两台电脑上有差异。请问你能说说你是怎么给dsdt打补丁吗？

**Comment by Qjbtiger** [comment]
谢谢！我自己先尝试一下！

**Comment by Qjbtiger** [comment]
你好，我按照你发的教程，目前系统能识别触摸板，但滑动缓慢而且一段时间后就会卡死，我用maclog查看系统日志发现，是系统没有识别到总线速度等信息，具体信息在图片中，请问你曾遇到过这样的情况吗？我试过网上几种解决办法都没有效果，请问你能不能分享下未编译前修改过的dsl文件看看（DSDT.dsl和SSDT*.dsl)，也许对我有所帮助。
非常感谢！
![522d9d7cb4a4c47d0c01896986eea54](https://user-images.githubusercontent.com/44047419/77218655-96438680-6b68-11ea-8ebe-51548fad40d8.jpg)

**Comment by longmiaohao** [comment]
我的dsdt原始文件在clover/acpi/origin，这个问题我没有遇到过，但是我觉得你可以用hackintool那个工具检测下你的系统信息，可能是只是config.list里需要打一个名称change的补丁就好，这个你得自己去尝试，多看调试信息，然后根据错误信息去推断或者Google/baidu，还有如果感觉卡顿，你需要在偏好设置/触摸板里面把智能缩放给干掉，这个设置关了会极大提高体验感，至少我是这样的

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Qjb8668 <notifications@github.com&gt;
发送时间: 2020年3月21日 11:38
收件人: longmiaohao/Asus-Fx60vm-clover <Asus-Fx60vm-clover@noreply.github.com&gt;
抄送: longmiaohao <1043213248@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[longmiaohao/Asus-Fx60vm-clover] 有个驱动导致logo重启 (#1)





 
你好，我按照你发的教程，目前系统能识别触摸板，但滑动缓慢而且一段时间后就会卡死，我用maclog查看系统日志发现，是系统没有识别到总线速度等信息，具体信息在图片中，请问你曾遇到过这样的情况吗？我试过网上几种解决办法都没有效果，请问你能不能分享下未编译前修改过的dsl文件看看（DSDT.dsl和SSDT*.dsl)，也许对我有所帮助。
 非常感谢！
