### ISSUE TITLE
老哥，华硕fx53vd可以用这个EFI吗

### ISSUE THREAD

**Issue by hanlei153** [longmiaohao/Asus-Fx60vm-clover#2]

**Comment by longmiaohao** [comment]
你好，这么跟你说吧，你只要能想办法装上系统，驱动问题只是要花点时间去找，我这里面的驱动也可以拿去试试，指不定就可以，有些驱动是通用的，但是有些不是，具体行不行，你可以看两个机型硬件的匹配程度，相近的都可以试试，这里我推荐你去用人家制作的专门用来装机的efi和镜像的整合资源，可以避开很多坑，由于我的显卡只支持到10.13.6，所以我下载了10.13.5的镜像，留一个号来测试升级，我把我的镜像连接贴出来，希望能帮到你！https://blog.daliansky.net/macOS-High-Sierra-10.13.5-17F77-Release-Version-with-Clover-4512-original-mirror.html
还有网上和github上有很多efi，你对应看看你自己型号的有没有现成的efi可以用吧，能省不少事儿的，祝你好运！
